/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    fun sum(a: Int, b:Int) : Int{
        return a + b
    }
}

fun main() {
    println("Hello World")
}
