/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {

    private val testSample : App = App()
    @Test fun appHasAGreeting() {
       val expected = 43
        assertEquals(expected, testSample.sum(42,1))

    }
}
